sudo: required
language: java
services:
- docker
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y protobuf-compiler
install:
- ./mvnw --projects bdse-kvnode clean package
- docker pull redis:3.2.11
- docker pull openjdk:8-jdk-alpine
script:
- ./mvnw --projects bdse-integration-tests --also-make test
